url: "menu.lolev.beer" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Today's Menu" # the name of your site, e.g. ACME Corp.

sass:
  sass_dir: _sass
  style: compressed
